-- 数据库初始化脚本

-- 创建数据库
CREATE DATABASE init;

-- 使用数据库
USE init;

-- 创建数据表
CREATE TABLE USER (
  USER_ID BIGINT NOT NULL AUTO_INCREMENT
  COMMENT '用户编号',
  USER_NAME VARCHAR(10) NOT NULL
  COMMENT '用户名',
  PASSWORD VARCHAR(10) NOT NULL
  COMMENT '密码',
  CREATE_TIME TIMESTAMP DEFAULT current_timestamp
  COMMENT '创建时间',
  PRIMARY KEY (USER_ID),
  KEY idx_user_id(USER_ID)
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = UTF8
  COMMENT '用户表';

-- 初始化数据
INSERT INTO USER (USER_NAME, PASSWORD) VALUES ('胖墩肥仔','123456');
INSERT INTO USER (USER_NAME, PASSWORD) VALUES ('我忘了叫啥66','123456');
INSERT INTO USER (USER_NAME, PASSWORD) VALUES ('真诚的坑货','123456');
INSERT INTO USER (USER_NAME, PASSWORD) VALUES ('逗你玩哈哈哈','123456');
INSERT INTO USER (USER_NAME, PASSWORD) VALUES ('小人物221','123456');